export const TABLE_COLUMN_COMMENTS = {
  // Common fields used across all tables
  COMMON: {
    ID: "Primary key identifier",
    CREATED_AT: "Timestamp when record was created",
    UPDATED_AT: "Timestamp when record was last updated",
    CREATED_BY: "ID of admin who created the record",
    UPDATED_BY: "ID of admin who last updated the record",
    DELETED_BY: "ID of admin who soft deleted the record",
    STATUS: "Record status (ACTIVE, INACTIVE, DELETED)",
    CREATED_BY_ADMIN: "Admin entity who created the record",
    UPDATED_BY_ADMIN: "Admin entity who last updated the record",
    DELETED_BY_ADMIN: "Admin entity who soft deleted the record",
  },

  // Users table
  USERS: {
    ID: "Primary key identifier",
    FULL_NAME: "User's complete name",
    PROFILE_PICTURE: "URL to user's profile image",
    EMAIL: "User's email address (unique)",
    COUNTRY_CODE: "Country calling code for phone number",
    PHONE: "User's phone number without country code",
    FULL_PHONE_NO: "Complete phone number with country code (unique)",
    PASSWORD: "Hashed user password",
    USER_TYPE: "Type of user (USER, ADMIN, etc.)",
    STATUS: "User account status",
    IS_FIRST_LOGIN: "Flag indicating if this is user's first login",
    DELETED_BY_ADMIN: "Flag indicating if user was deleted by admin",
    LOGIN_TYPE: "Method used for login (EMAIL, PHONE, SOCIAL)",
    GENDER: "User's gender",
    SELECTED_LANGUAGE: "User's preferred language",
    DOB: "User's date of birth",
    IS_GUEST: "Flag indicating if user is a guest",
    GUEST_ID: "Unique identifier for guest users",
    PLATFORM: "Platform used for registration (IOS, ANDROID, WEB)",
    SOCIAL_ACCOUNT_TYPE: "Type of social account used for login",
    TIER_ID: "User's loyalty tier ID",
    POINTS: "User's loyalty points balance",
    TOTAL_SPENT: "Total amount spent by user",
    LAST_ORDER_DATE: "Date of user's last order",
    REFERRAL_CODE: "User's unique referral code",
    REFERRED_BY: "Referral code of user who referred this user",
    REFERRAL_POINTS: "Points earned from referrals",
    PREFERRED_BRANCH_ID: "User's preferred branch ID",
    NOTIFICATION_SETTINGS: "User's notification preferences",
    CREATED_AT: "Timestamp when user account was created",
    UPDATED_AT: "Timestamp when user account was last updated",
  },

  // Admins table
  ADMINS: {
    ID: "Primary key identifier",
    ADMIN_ID: "Unique admin identifier",
    EMAIL: "Admin's email address",
    PASSWORD: "Hashed admin password",
    SALT: "Salt used for password hashing",
    FULL_NAME: "Admin's complete name",
    USER_TYPE: "Type of admin user",
    PROFILE_PICTURE: "URL to admin's profile image",
    COUNTRY_CODE: "Country calling code for phone number",
    PHONE: "Admin's phone number without country code",
    FULL_PHONE_NO: "Complete phone number with country code",
    FORCE_PASSWORD_CHANGE: "Flag to force password change on next login",
    IS_NEW: "Flag indicating if admin is new",
    ROLE_ID: "Admin's role ID",
    BRANCH_ID: "Branch ID where admin works",
    CREATED_AT: "Timestamp when admin account was created",
    UPDATED_AT: "Timestamp when admin account was last updated",
  },

  // Items table
  ITEMS: {
    ID: "Primary key identifier",
    ITEM_ID: "Unique item identifier",
    IS_POM: "Flag indicating if item is Prescription Only Medicine",
    IS_FORCE_2HR: "Flag indicating if item requires 2-hour delivery",
    IS_3RD_PARTY: "Flag indicating if item is from third party",
    IS_CUSTOMER_REVIEW_ALLOWED: "Flag allowing customer reviews",
    NAME_EN: "Item name in English",
    NAME_AR: "Item name in Arabic",
    PRICE: "Item's base price",
    CATEGORY_ID: "ID of item's category",
    SKU: "Stock Keeping Unit identifier",
    BRAND_ID: "ID of item's brand",
    METRIC: "Item quantity metric value",
    METRIC_UNIT: "Unit of measurement for metric",
    CONCERN_ID: "ID of health concern this item addresses",
    FLASH_SALES_ID: "ID of flash sale this item belongs to",
    BAR_CODE: "Product barcode",
    DISPLAY_ORDER: "Order for displaying items",
    STOCK_ALERT_THRESHOLD: "Minimum stock level before alert",
    PURCHASED_COUNT: "Number of times item was purchased",
    DISCOUNT: "Discount amount on item",
    PRICE_AFTER_DISCOUNT: "Price after applying discount",
    PROMOTION_ID: "ID of active promotion",
    PROMOTION_TYPE: "Type of promotion applied",
    PROMOTION_DISCOUNT: "Discount from promotion",
    DISCOUNT_AFTER_PROMOTION: "Final discount after promotion",
    MAX_LIMIT_PER_ITEM: "Maximum quantity per order",
    KEY_WORDS_EN: "Search keywords in English",
    KEY_WORDS_AR: "Search keywords in Arabic",
    BDI_ID: "Business Data Integration ID",
    DESCRIPTION_EN: "Item description in English",
    DESCRIPTION_AR: "Item description in Arabic",
    INTEGRATIONS_EN: "Integration instructions in English",
    INTEGRATIONS_AR: "Integration instructions in Arabic",
    SIDE_EFFECTS_EN: "Side effects description in English",
    SIDE_EFFECTS_AR: "Side effects description in Arabic",
    HOW_TO_USE_EN: "Usage instructions in English",
    HOW_TO_USE_AR: "Usage instructions in Arabic",
    BANNER_IMAGE: "Main banner image for item",
    VARIATION_IMAGE: "Image showing item variations",
    IMAGES: "Array of item images",
    CREATED_AT: "Timestamp when item was created",
    UPDATED_AT: "Timestamp when item was last updated",
  },

  // Categories table
  CATEGORIES: {
    ID: "Primary key identifier",
    CATEGORY_ID: "Unique category identifier",
    NAME_EN: "Category name in English",
    NAME_AR: "Category name in Arabic",
    DISPLAY_ORDER: "Order for displaying categories",
    IMAGE: "Category's main image",
    BANNER: "Category's banner images",
    CREATED_AT: "Timestamp when category was created",
    UPDATED_AT: "Timestamp when category was last updated",
  },

  // Sub Categories table
  SUB_CATEGORIES: {
    ID: "Primary key identifier",
    SUB_CATEGORY_ID: "Unique sub-category identifier",
    NAME_EN: "Sub-category name in English",
    NAME_AR: "Sub-category name in Arabic",
    IMAGE: "Sub-category's main image",
    DISPLAY_ORDER: "Order for displaying sub-categories",
    BANNER: "Sub-category's banner images",
    CATEGORY_ID: "ID of parent category",
    CREATED_AT: "Timestamp when sub-category was created",
    UPDATED_AT: "Timestamp when sub-category was last updated",
  },

  // Brands table
  BRANDS: {
    ID: "Primary key identifier",
    BRAND_ID: "Unique brand identifier",
    LOGO: "URL to brand logo",
    NAME_EN: "Brand name in English",
    NAME_AR: "Brand name in Arabic",
    DISPLAY_ORDER: "Order for displaying brands",
    DESCRIPTION_EN: "Brand description in English",
    DESCRIPTION_AR: "Brand description in Arabic",
    IS_FEATURE_BRAND: "Flag indicating if brand is featured",
    IS_NEW_BRAND: "Flag indicating if brand is new",
    SHOW_NEW_BRAND_DAYS: "Number of days to show as new brand",
    BRAND_DISPLAY_ORDER: "Custom display order for brand",
    IS_BRAND_DISPLAY_ORDER: "Flag to use custom display order",
    CREATED_AT: "Timestamp when brand was created",
    UPDATED_AT: "Timestamp when brand was last updated",
  },

  // Inventory table
  INVENTORY: {
    ID: "Primary key identifier",
    INVENTORY_ID: "Unique inventory identifier",
    ITEM_ID: "ID of the item",
    BRANCH_ID: "ID of the branch",
    QUANTITY: "Available quantity in stock",
    SKU: "Stock Keeping Unit identifier",
    CREATED_AT: "Timestamp when inventory record was created",
    UPDATED_AT: "Timestamp when inventory record was last updated",
  },

  // Cart table
  CART: {
    ID: "Primary key identifier",
    CART_ID: "Unique cart identifier",
    USER_ID: "ID of the cart owner",
    TOTAL_PRICE: "Total price of all items in cart",
    DISCOUNT: "Total discount applied to cart",
    FINAL_PRICE: "Final price after discounts",
    DELIVERY_FEE: "Delivery fee for the order",
    FREE_DELIVERY: "Flag indicating if delivery is free",
    POINTS_USED: "Loyalty points used in cart",
    NOTE: "Special notes for the order",
    CREATED_AT: "Timestamp when cart was created",
    UPDATED_AT: "Timestamp when cart was last updated",
  },

  // Cart Items table
  CART_ITEMS: {
    ID: "Primary key identifier",
    CART_ID: "ID of the parent cart",
    ITEM_ID: "ID of the item in cart",
    QUANTITY: "Quantity of item in cart",
    IS_FREE: "Flag indicating if item is free",
    PARENT_ITEM_ID: "ID of parent item for bundled items",
    CREATED_AT: "Timestamp when cart item was added",
    UPDATED_AT: "Timestamp when cart item was last updated",
  },

  // Promotions table
  PROMOTIONS: {
    ID: "Primary key identifier",
    PROMOTION_CODE_ID: "Unique promotion code identifier",
    CODE: "Promotion code string (unique)",
    NAME_EN: "Promotion name in English",
    NAME_AR: "Promotion name in Arabic",
    DESCRIPTION_EN: "Promotion description in English",
    DESCRIPTION_AR: "Promotion description in Arabic",
    OFFLINE_DESCRIPTION: "Description for offline use",
    IS_SHOW_ON_APP_ENABLED: "Flag to show promotion in app",
    IS_FREE_DELIVERY_ENABLED: "Flag for free delivery promotion",
    TARGET_USER_TYPE: "Type of users this promotion targets",
    VALUE: "Promotion value (discount amount/percentage)",
    USAGE_PER_CUSTOMER: "Maximum usage per customer",
    MAX_USAGE_CAP_ACROSS_ALL: "Maximum total usage across all customers",
    ORDER_AMOUNT_MIN: "Minimum order amount required",
    ORDER_AMOUNT_MAX: "Maximum order amount for promotion",
    ACTIVE_FROM: "Promotion start date and time",
    ACTIVE_TO: "Promotion end date and time",
    APPLY_TYPE: "How promotion is applied (SUBTOTAL, SPECIFIC_BASKET)",
    IS_POM_ITEMS_EXCLUDED: "Flag to exclude POM items from promotion",
    TYPE: "Type of promotion (PERCENTAGE, FLAT, BOGO)",
    CREATED_AT: "Timestamp when promotion was created",
    UPDATED_AT: "Timestamp when promotion was last updated",
  },

  // Bundles table
  BUNDLES: {
    ID: "Primary key identifier",
    BUNDLE_ID: "Unique bundle identifier",
    BUNDLE_SKU: "Bundle's SKU identifier",
    NAME_EN: "Bundle name in English",
    NAME_AR: "Bundle name in Arabic",
    CATEGORY_ID: "ID of bundle's category",
    TAG_IDS: "Array of tag IDs associated with bundle",
    ORIGINAL_PRICE: "Original total price of bundle",
    FINAL_PRICE: "Final price after discounts",
    DISCOUNT_PERCENTAGE: "Discount percentage applied",
    ITEMS_PRICE_SNAPSHOT: "Snapshot of item prices when bundle was created",
    STATUS: "Bundle status (ACTIVE, INACTIVE, etc.)",
    DESCRIPTION_EN: "Bundle description in English",
    DESCRIPTION_AR: "Bundle description in Arabic",
    INGREDIENTS_EN: "Bundle ingredients in English",
    INGREDIENTS_AR: "Bundle ingredients in Arabic",
    SIDE_EFFECTS_EN: "Bundle side effects in English",
    SIDE_EFFECTS_AR: "Bundle side effects in Arabic",
    HOW_TO_USE_EN: "Bundle usage instructions in English",
    HOW_TO_USE_AR: "Bundle usage instructions in Arabic",
    BANNER_IMAGE: "Bundle's main banner image",
    VARIATION_IMAGE: "Bundle's variation image",
    IMAGES: "Array of bundle images",
    CREATED_AT: "Timestamp when bundle was created",
    UPDATED_AT: "Timestamp when bundle was last updated",
  },

  // Bundle Assign Items table
  BUNDLE_ASSIGN_ITEMS: {
    ID: "Primary key identifier",
    BUNDLE_ID: "ID of the bundle",
    PRODUCT_ID: "ID of the product in bundle",
    DISPLAY_ORDER: "Order for displaying items in bundle",
    CREATED_AT: "Timestamp when item was assigned to bundle",
    UPDATED_AT: "Timestamp when assignment was last updated",
  },

  // Branches table
  BRANCHES: {
    ID: "Primary key identifier",
    BRANCH_ID: "Unique branch identifier",
    IMAGE: "URL to branch image",
    NAME_EN: "Branch name in English",
    NAME_AR: "Branch name in Arabic",
    COUNTRY_CODE: "Branch country calling code",
    PHONE: "Branch phone number",
    MODE: "Branch delivery mode",
    ZONE_ID: "ID of branch's zone",
    AVAILABILITY_ID: "ID of branch's availability settings",
    IS_HUB: "Flag indicating if branch is a hub",
    CREATED_AT: "Timestamp when branch was created",
    UPDATED_AT: "Timestamp when branch was last updated",
  },

  // User Addresses table
  USER_ADDRESSES: {
    ID: "Primary key identifier",
    USER_ID: "ID of the address owner",
    TYPE: "Type of address (HOME, WORK, etc.)",
    NAME: "Address name/label",
    HOUSE_OR_BUILDING: "House or building number",
    APARTMENT_OR_COMPANY: "Apartment or company name",
    FLOOR: "Floor number",
    STREET: "Street name",
    DIRECTION: "Directional instructions",
    IS_DEFAULT: "Flag indicating if this is default address",
    LATITUDE: "Geographic latitude coordinate",
    LONGITUDE: "Geographic longitude coordinate",
    GOOGLE_STREET: "Google Maps street address",
    ZONE_ID: "ID of delivery zone",
    ZONE_NAME: "Name of delivery zone",
    BRANCH_ID: "ID of serving branch",
    BRANCH_NAME: "Name of serving branch",
    CREATED_AT: "Timestamp when address was created",
    UPDATED_AT: "Timestamp when address was last updated",
  },

  // Tags table
  TAGS: {
    ID: "Primary key identifier",
    TAG_ID: "Unique tag identifier",
    TITLE_EN: "Tag title in English",
    TITLE_AR: "Tag title in Arabic",
    CREATED_AT: "Timestamp when tag was created",
    UPDATED_AT: "Timestamp when tag was last updated",
  },

  // Concerns table
  CONCERNS: {
    ID: "Primary key identifier",
    CONCERN_ID: "Unique concern identifier",
    IMAGE: "URL to concern image",
    TITLE_EN: "Concern title in English",
    TITLE_AR: "Concern title in Arabic",
    DISPLAY_ORDER: "Order for displaying concerns",
    ITEM_COUNT: "Number of items in this concern",
    CREATED_AT: "Timestamp when concern was created",
    UPDATED_AT: "Timestamp when concern was last updated",
  },

  // Flash Sales table
  FLASH_SALES: {
    ID: "Primary key identifier",
    FLASH_SALE_ID: "Unique flash sale identifier",
    TITLE_EN: "Flash sale title in English",
    TITLE_AR: "Flash sale title in Arabic",
    BANNER_IMAGE_EN: "Banner image for English",
    BANNER_IMAGE_AR: "Banner image for Arabic",
    DISPLAY_STYLE: "Style for displaying flash sale",
    DATE_FROM: "Flash sale start date and time",
    DATE_TO: "Flash sale end date and time",
    HOMEPAGE_SECTION_ID: "ID of homepage section",
    FLASH_SALE_TIMER_SHOW: "Flag to show countdown timer",
    SHOW_ONLY_ITEMS_WITH_ACTIVE_OFFERS:
      "Flag to show only items with active offers",
    CREATED_AT: "Timestamp when flash sale was created",
    UPDATED_AT: "Timestamp when flash sale was last updated",
  },

  // Tiers table
  TIERS: {
    ID: "Primary key identifier",
    TITLE: "Tier title/name",
    MIN_FREQUENCY_RANGE: "Minimum frequency range for tier",
    MAX_FREQUENCY_RANGE: "Maximum frequency range for tier",
    START_DATE: "Tier start date",
    END_DATE: "Tier end date",
    MIN_LIFETIME_SPEND: "Minimum lifetime spend for tier",
    MAX_LIFETIME_SPEND: "Maximum lifetime spend for tier",
    COLOR_SCHEME: "Color scheme for tier display",
    CREATED_AT: "Timestamp when tier was created",
    UPDATED_AT: "Timestamp when tier was last updated",
  },

  // Roles table
  ROLES: {
    ID: "Primary key identifier",
    ROLE_ID: "Unique role identifier",
    NAME: "Role name",
    DESCRIPTION: "Role description",
    IS_PHARMACIST: "Flag indicating if role is for pharmacist",
    IS_SUPER_ADMIN: "Flag indicating if role is super admin",
    CREATED_AT: "Timestamp when role was created",
    UPDATED_AT: "Timestamp when role was last updated",
  },

  // Permissions table
  PERMISSIONS: {
    ID: "Primary key identifier",
    NAME: "Permission name (unique)",
    DESCRIPTION: "Permission description",
    MODULE: "Module this permission belongs to",
    ACTION: "Action this permission allows",
    CREATED_AT: "Timestamp when permission was created",
    UPDATED_AT: "Timestamp when permission was last updated",
  },

  // Suppliers table
  SUPPLIERS: {
    ID: "Primary key identifier",
    SUPPLIER_ID: "Unique supplier identifier",
    TITLE_EN: "Supplier name in English",
    TITLE_AR: "Supplier name in Arabic",
    CREATED_AT: "Timestamp when supplier was created",
    UPDATED_AT: "Timestamp when supplier was last updated",
  },

  // Image Library table
  IMAGE_LIBRARY: {
    ID: "Primary key identifier",
    MEDIA_ID: "Unique media identifier",
    MEDIA_NAME: "Name of the media file",
    MEDIA_URL: "URL to the media file",
    TYPE: "Type of media (IMAGE, VIDEO, etc.)",
    CREATED_AT: "Timestamp when media was uploaded",
    UPDATED_AT: "Timestamp when media was last updated",
  },

  // Popup Banners table
  POPUP_BANNERS: {
    ID: "Primary key identifier",
    BANNER_ID: "Unique banner identifier",
    BANNER_NAME_EN: "Banner name in English",
    BANNER_NAME_AR: "Banner name in Arabic",
    BANNER_IMAGE_EN: "Banner image URL for English",
    BANNER_IMAGE_AR: "Banner image URL for Arabic",
    NAVIGATION_URL: "URL to navigate when banner is clicked",
    TARGET_TYPE: "Type of users to target",
    START_DATE_TIME: "Banner start date and time",
    END_DATE_TIME: "Banner end date and time",
    DISPLAY_FREQUENCY: "How often to display banner",
    CUSTOM_FREQUENCY_COUNT: "Custom frequency count",
    CREATED_AT: "Timestamp when banner was created",
    UPDATED_AT: "Timestamp when banner was last updated",
  },

  // Notification Logs table
  NOTIFICATION_LOGS: {
    ID: "Primary key identifier",
    RECIPIENT: "Notification recipient",
    SUBJECT: "Notification subject",
    CONTENT: "Notification content",
    TEMPLATE_TYPE: "Type of notification template",
    NOTIFICATION_STATUS: "Status of notification",
    ERROR_MESSAGE: "Error message if notification failed",
    TEMPLATE_DATA: "Data used in notification template",
    SENT_AT: "Timestamp when notification was sent",
    RETRY_COUNT: "Number of retry attempts",
    MAX_RETRIES: "Maximum number of retries",
    LAST_RETRY_AT: "Timestamp of last retry attempt",
    USER_ID: "ID of user who received notification",
    MODE: "Notification mode (EMAIL, SMS, PUSH)",
    CREATED_AT: "Timestamp when notification was created",
    UPDATED_AT: "Timestamp when notification was last updated",
  },

  // Algolia Sync table
  ALGOLIA_SYNC: {
    ID: "Primary key identifier",
    STATUS: "Sync status (PENDING, IN_PROGRESS, COMPLETED, FAILED)",
    IDS: "Array of IDs to sync",
    TYPE: "Type of entity to sync",
    ACTION: "Action to perform (CREATED, UPDATED, DELETED)",
    SYNCED: "Flag indicating if sync is complete",
    TRIES_REMAINING: "Number of retry attempts remaining",
    ERROR_MESSAGE: "Error message if sync failed",
    LAST_ATTEMPT_AT: "Timestamp of last sync attempt",
    CREATED_AT: "Timestamp when sync was created",
    UPDATED_AT: "Timestamp when sync was last updated",
  },

  // Application Settings table
  APPLICATION_SETTINGS: {
    ID: "Primary key identifier",
    APPLICATION_SETTING_ID: "Unique application setting identifier",
    IS_INVENTORY_CONTROL_ENABLED: "Flag to enable inventory control",
    IS_EMERGENCY_CONTROL_ENABLED: "Flag to enable emergency control",
    IS_SMART_ITEM_DISPLAY_ENABLED: "Flag to enable smart item display",
    SMART_ITEM_MOVEMENT: "Smart item movement settings",
    SMART_ITEM_IMC: "Smart item IMC settings",
    IS_PROXIMITY_DETECTION_ENABLED: "Flag to enable proximity detection",
    PROXIMITY_RANGE_METER: "Proximity detection range in meters",
    IS_REFERRAL_PROGRAM_ENABLED: "Flag to enable referral program",
    REFERRAL_BONUS_FOR_REFERRER: "Bonus points for referrer",
    REFERRAL_BONUS_FOR_NEW_USER: "Bonus points for new user",
    REFERRAL_BONUS_TRIGGER_CONDITION: "Condition to trigger referral bonus",
    CREATED_AT: "Timestamp when setting was created",
    UPDATED_AT: "Timestamp when setting was last updated",
  },

  // Application Brand table
  APPLICATION_BRAND: {
    ID: "Primary key identifier",
    APPLICATION_CONFIG_ID: "Unique application config identifier",
    LOGO: "Application logo URL",
    TITLE_EN: "Application title in English",
    TITLE_AR: "Application title in Arabic",
    SHOW_ON_IOS: "Flag to show on iOS",
    SHOW_ON_ANDROID: "Flag to show on Android",
    CREATED_AT: "Timestamp when brand config was created",
    UPDATED_AT: "Timestamp when brand config was last updated",
  },

  // Application Terms table
  APPLICATION_TERMS: {
    ID: "Primary key identifier",
    TERMS_ID: "Unique terms identifier",
    TITLE_EN: "Terms title in English",
    TITLE_AR: "Terms title in Arabic",
    CONTENT_EN: "Terms content in English",
    CONTENT_AR: "Terms content in Arabic",
    VERSION: "Terms version number",
    IS_ACTIVE: "Flag indicating if terms are active",
    CREATED_AT: "Timestamp when terms were created",
    UPDATED_AT: "Timestamp when terms were last updated",
  },

  // Email Template table
  EMAIL_TEMPLATE: {
    ID: "Primary key identifier",
    TEMPLATE_ID: "Unique template identifier",
    NAME: "Template name",
    SUBJECT: "Email subject template",
    CONTENT: "Email content template",
    TYPE: "Template type",
    IS_ACTIVE: "Flag indicating if template is active",
    CREATED_AT: "Timestamp when template was created",
    UPDATED_AT: "Timestamp when template was last updated",
  },

  // Import Export Progress table
  IMPORT_EXPORT_PROGRESS: {
    ID: "Primary key identifier",
    PROGRESS_ID: "Unique progress identifier",
    USER_ID: "ID of user who initiated the process",
    TYPE: "Type of process (IMPORT, EXPORT)",
    STATUS: "Process status",
    TOTAL_RECORDS: "Total number of records to process",
    PROCESSED_RECORDS: "Number of records processed",
    FAILED_RECORDS: "Number of records that failed",
    FILE_NAME: "Name of the file being processed",
    ERROR_MESSAGE: "Error message if process failed",
    CREATED_AT: "Timestamp when process was started",
    UPDATED_AT: "Timestamp when process was last updated",
  },

  // Session table
  SESSION: {
    ID: "Primary key identifier",
    SESSION_ID: "Unique session identifier",
    USER_ID: "ID of the user",
    TOKEN: "Session token",
    EXPIRES_AT: "Session expiration timestamp",
    IS_ACTIVE: "Flag indicating if session is active",
    IP_ADDRESS: "IP address of the session",
    USER_AGENT: "User agent string",
    CREATED_AT: "Timestamp when session was created",
    UPDATED_AT: "Timestamp when session was last updated",
  },

  // Admin Session table
  ADMIN_SESSION: {
    ID: "Primary key identifier",
    SESSION_ID: "Unique session identifier",
    ADMIN_ID: "ID of the admin",
    TOKEN: "Session token",
    EXPIRES_AT: "Session expiration timestamp",
    IS_ACTIVE: "Flag indicating if session is active",
    IP_ADDRESS: "IP address of the session",
    USER_AGENT: "User agent string",
    CREATED_AT: "Timestamp when session was created",
    UPDATED_AT: "Timestamp when session was last updated",
  },

  // User Session table
  USER_SESSION: {
    ID: "Primary key identifier",
    SESSION_ID: "Unique session identifier",
    USER_ID: "ID of the user",
    TOKEN: "Session token",
    EXPIRES_AT: "Session expiration timestamp",
    IS_ACTIVE: "Flag indicating if session is active",
    IP_ADDRESS: "IP address of the session",
    USER_AGENT: "User agent string",
    CREATED_AT: "Timestamp when session was created",
    UPDATED_AT: "Timestamp when session was last updated",
  },

  // Branch Address table
  BRANCH_ADDRESS: {
    ID: "Primary key identifier",
    ADDRESS_ID: "Unique address identifier",
    BRANCH_ID: "ID of the branch",
    ADDRESS_EN: "Address in English",
    ADDRESS_AR: "Address in Arabic",
    SHOW_ON_LOCATOR: "Flag to show on locator",
    SHOW_ON_STORE_LOCATOR: "Flag to show on store locator",
    LOCATION: "Location description",
    LATITUDE: "Geographic latitude coordinate",
    LONGITUDE: "Geographic longitude coordinate",
    CREATED_AT: "Timestamp when address was created",
    UPDATED_AT: "Timestamp when address was last updated",
  },

  // Branch Availability table
  BRANCH_AVAILABILITY: {
    ID: "Primary key identifier",
    AVAILABILITY_ID: "Unique availability identifier",
    BRANCH_ID: "ID of the branch",
    CONTACT_PERSON_NAME: "Contact person name",
    CONTACT_PERSON_PHONE: "Contact person phone",
    CONTACT_PERSON_EMAIL: "Contact person email",
    EXTENSION: "Phone extension",
    IS_ALL_TIME_OPEN: "Flag indicating if branch is open 24/7",
    CREATED_AT: "Timestamp when availability was created",
    UPDATED_AT: "Timestamp when availability was last updated",
  },

  // Branch Timings table
  BRANCH_TIMINGS: {
    ID: "Primary key identifier",
    TIMING_ID: "Unique timing identifier",
    BRANCH_ID: "ID of the branch",
    DAY: "Day of the week",
    START_TIME: "Opening time",
    END_TIME: "Closing time",
    IS_OPEN: "Flag indicating if branch is open on this day",
    CREATED_AT: "Timestamp when timing was created",
    UPDATED_AT: "Timestamp when timing was last updated",
  },

  // Zone table
  ZONES: {
    ID: "Primary key identifier",
    ZONE_ID: "Unique zone identifier",
    NAME_EN: "Zone name in English",
    NAME_AR: "Zone name in Arabic",
    BRANCH_ID: "ID of the associated branch",
    CREATED_AT: "Timestamp when zone was created",
    UPDATED_AT: "Timestamp when zone was last updated",
  },

  // Geo Point table
  GEO_POINTS: {
    ID: "Primary key identifier",
    POINT_ID: "Unique geo point identifier",
    ZONE_ID: "ID of the zone",
    LATITUDE: "Geographic latitude coordinate",
    LONGITUDE: "Geographic longitude coordinate",
    CREATED_AT: "Timestamp when point was created",
    UPDATED_AT: "Timestamp when point was last updated",
  },
};
